#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  program which does not use PID and carries out certain functions
*/


//function to turn the robot by 90 degrees to the left
	void turn90degreesLeft()
{	
	setMotorSpeed(leftMotor, -10);	//Set the leftMotor (motor1) to 10% of full power backwards (-10)
	setMotorSpeed(rightMotor, 10);  //Set the rightMotor (motor6) to forward at 10% of full power (10)
  	sleep(750);			//Wait for 75% of a second before finishing the function.
}
  

//function to turn the robot by 90 degrees to the right  
	void turn90degreesRight()
{
        setMotorSpeed(leftMotor, 10);	  //Set the leftMotor (motor1) to 10% of full power forwards (10)
	setMotorSpeed(rightMotor, -10);   //Set the rightMotor (motor6) to backwards at 10% of full power (-10)
  	sleep(750);			  //Wait for 75% of a second before finishing the function.
}
  
//function to make the robot go forward for one second
	void  goForward1second()
{
  	setMotorSpeed(leftMotor, 50);	  //Set the leftMotor (motor1) to forward at half of full power (50)
	setMotorSpeed(rightMotor, 50);    //Set the rightMotor (motor6) to forward at half of full power (50)
  	sleep(1000);			  //Wait for 1 second before finishing the function.
}
  
//function to make the robot swing by 90 degrees
	void  swingLeft90degrees()
{
	setMotorSpeed(leftMotor, 0);	  //Set the leftMotor (motor1) to off (0)
        setMotorSpeed(rightMotor, 20);    //turn the right motor to 20% of full power forward (20)
  	sleep(750);                       //Wait for 75% of a second before finishing the function.
}
  
//function to make the robot do a 90 degrees swing to the right
	void  swingRight90degrees()
{
        setMotorSpeed(leftMotor, 20);	  //Set the leftMotor (motor1) to 20% of full power forwards (20)
	setMotorSpeed(rightMotor, 0);     //Set the rightMotor (motor6) to off (0)
  	sleep(750);			  //Wait for 75% of a second before finishing the function.
}

//function to make robot go backwards for one second  
	void   reverse1second()
{
  	setMotorSpeed(leftMotor, -100);	  //Set the leftMotor (motor1) to backwards at full power (-100)
	setMotorSpeed(rightMotor, -100);  //Set the rightMotor (motor6) to backwards at full power (-100)
  	sleep(1000);			  //Wait for 1 second before finishing the function.
}


task main()
{
	//calling the functions	
	turn90degreesLeft();
	sleep(3000);
	turn90degreesRight();
	sleep(3000);
	goForward1second();	

	swingRight90degrees();
	sleep(3000);
	swingLeft90degrees();
	sleep(3000);
	reverse1second();
}
