#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//program that uses functions that use PID


//Synch two motors for a specified amount of time
//function that makes the robot go straight
	void straight()
{
	setMotorSyncTime(leftMotor, rightMotor, 0, 3000, 50);
	sleep(1000); //wait for one second before finishing the function
}

//function that makes the robot turn right
	void right()
{
	setMotorSyncTime(leftMotor, rightMotor, 50, 1500, 50);
	sleep(1500); //wait for 1.5 seconds before finishing the function
}

//function that  makes the robot turn left
	void left()
{
	setMotorSyncTime(leftMotor, rightMotor, -50, 1500, 50);
	sleep(1500); //wait for 1.5 seconds before finishing the function
}

//function that makes the robot go backwards
	void back()
{
	setMotorSyncTime(leftMotor, rightMotor, 0, 3000, -50);
	sleep(1000); //wait for 1 second before finishing the function
}


task main()
{
	//calling the functions
	straight();
	right();
	left();
	back();
}
